services:
#    thewbb_form.example:
#        class: Thewbb\FormBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    thewbb.form.type.multi_upload:
        class: Thewbb\FormBundle\Form\Type\MultiUploadType
        arguments:
            - @router
        tags:
            - { name: form.type, alias: multi_upload }